# name: Publish to NPM and GitHub registry

# on:
#   release:
#     types: [created]

# jobs:
#   publish:
#     uses: stegripe/workflows/.github/workflows/pnpm-publish.yml@main
#     secrets: inherit
